### ISSUE TITLE
Linking to your guide

### ISSUE THREAD

**Issue by Vyrastas** [ERNE196077/qemu_openthread_borderrouter#1]
Hi @ERNE196077 , this is Jeff from the OpenThread team.  Sorry for the delay in responding to the feedback you sent us at openthread.io about this repo.  We would love to link out to your QEMU guide here, if you would allow it.  This is an interesting use case that some of our users might find helpful.

You might want to check that it still works as written, as the team has changed some things in /script/setup (for instance, it will attempt to configure a Wi-Fi AP using Network Manager as part of the script, which I don't believe is supported by this type of emulation).  Would you mind making sure the guide is still valid?

Thanks, and let me know what you think.

Jeff

**Comment by ERNE196077** [comment]
Dang! Please take my apologizes.... 
Let me make sure about it and do the modifications accordingly. It should take me few hours. 
Thanks for your reply btw @Vyrastas ! :)

Ernesto

**Comment by Vyrastas** [comment]
No worries!  Just let me know if the guide is still valid based on the current version of OTBR, and we'll go ahead and link it.  :)

**Comment by ERNE196077** [comment]
OK.. Modified the read me for the current version of OTBR... and the script and kernel are still valid for the latest Raspbian available today. Feel free to link it and again, Thanks for your patience :+1:

**Comment by Vyrastas** [comment]
Posted!  https://openthread.io/guides/border-router#community_projects
